/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as AnuncieRouteImport } from './routes/anuncie'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PerfilIdRouteImport } from './routes/perfil.$id'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDenunciasRouteImport } from './routes/admin.denuncias'
import { Route as AdminPerfisIndexRouteImport } from './routes/admin.perfis.index'
import { Route as AdminPerfisNovoRouteImport } from './routes/admin.perfis.novo'
import { Route as AdminPerfilIdRouteImport } from './routes/admin.perfil.$id'
import { Route as AdminPerfisIdEditarRouteImport } from './routes/admin.perfis.$id.editar'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AnuncieRoute = AnuncieRouteImport.update({
  id: '/anuncie',
  path: '/anuncie',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PerfilIdRoute = PerfilIdRouteImport.update({
  id: '/perfil/$id',
  path: '/perfil/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDenunciasRoute = AdminDenunciasRouteImport.update({
  id: '/denuncias',
  path: '/denuncias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerfisIndexRoute = AdminPerfisIndexRouteImport.update({
  id: '/perfis/',
  path: '/perfis/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerfisNovoRoute = AdminPerfisNovoRouteImport.update({
  id: '/perfis/novo',
  path: '/perfis/novo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerfilIdRoute = AdminPerfilIdRouteImport.update({
  id: '/perfil/$id',
  path: '/perfil/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerfisIdEditarRoute = AdminPerfisIdEditarRouteImport.update({
  id: '/perfis/$id/editar',
  path: '/perfis/$id/editar',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/anuncie': typeof AnuncieRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/admin/denuncias': typeof AdminDenunciasRoute
  '/admin/login': typeof AdminLoginRoute
  '/perfil/$id': typeof PerfilIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/perfil/$id': typeof AdminPerfilIdRoute
  '/admin/perfis/novo': typeof AdminPerfisNovoRoute
  '/admin/perfis/': typeof AdminPerfisIndexRoute
  '/admin/perfis/$id/editar': typeof AdminPerfisIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anuncie': typeof AnuncieRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/admin/denuncias': typeof AdminDenunciasRoute
  '/admin/login': typeof AdminLoginRoute
  '/perfil/$id': typeof PerfilIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/perfil/$id': typeof AdminPerfilIdRoute
  '/admin/perfis/novo': typeof AdminPerfisNovoRoute
  '/admin/perfis': typeof AdminPerfisIndexRoute
  '/admin/perfis/$id/editar': typeof AdminPerfisIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/anuncie': typeof AnuncieRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/admin/denuncias': typeof AdminDenunciasRoute
  '/admin/login': typeof AdminLoginRoute
  '/perfil/$id': typeof PerfilIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/perfil/$id': typeof AdminPerfilIdRoute
  '/admin/perfis/novo': typeof AdminPerfisNovoRoute
  '/admin/perfis/': typeof AdminPerfisIndexRoute
  '/admin/perfis/$id/editar': typeof AdminPerfisIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/anuncie'
    | '/privacidade'
    | '/termos'
    | '/admin/denuncias'
    | '/admin/login'
    | '/perfil/$id'
    | '/admin/'
    | '/admin/perfil/$id'
    | '/admin/perfis/novo'
    | '/admin/perfis/'
    | '/admin/perfis/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anuncie'
    | '/privacidade'
    | '/termos'
    | '/admin/denuncias'
    | '/admin/login'
    | '/perfil/$id'
    | '/admin'
    | '/admin/perfil/$id'
    | '/admin/perfis/novo'
    | '/admin/perfis'
    | '/admin/perfis/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/anuncie'
    | '/privacidade'
    | '/termos'
    | '/admin/denuncias'
    | '/admin/login'
    | '/perfil/$id'
    | '/admin/'
    | '/admin/perfil/$id'
    | '/admin/perfis/novo'
    | '/admin/perfis/'
    | '/admin/perfis/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnuncieRoute: typeof AnuncieRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  PerfilIdRoute: typeof PerfilIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anuncie': {
      id: '/anuncie'
      path: '/anuncie'
      fullPath: '/anuncie'
      preLoaderRoute: typeof AnuncieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/perfil/$id': {
      id: '/perfil/$id'
      path: '/perfil/$id'
      fullPath: '/perfil/$id'
      preLoaderRoute: typeof PerfilIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/denuncias': {
      id: '/admin/denuncias'
      path: '/denuncias'
      fullPath: '/admin/denuncias'
      preLoaderRoute: typeof AdminDenunciasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/perfis/': {
      id: '/admin/perfis/'
      path: '/perfis'
      fullPath: '/admin/perfis/'
      preLoaderRoute: typeof AdminPerfisIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/perfis/novo': {
      id: '/admin/perfis/novo'
      path: '/perfis/novo'
      fullPath: '/admin/perfis/novo'
      preLoaderRoute: typeof AdminPerfisNovoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/perfil/$id': {
      id: '/admin/perfil/$id'
      path: '/perfil/$id'
      fullPath: '/admin/perfil/$id'
      preLoaderRoute: typeof AdminPerfilIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/perfis/$id/editar': {
      id: '/admin/perfis/$id/editar'
      path: '/perfis/$id/editar'
      fullPath: '/admin/perfis/$id/editar'
      preLoaderRoute: typeof AdminPerfisIdEditarRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDenunciasRoute: typeof AdminDenunciasRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPerfilIdRoute: typeof AdminPerfilIdRoute
  AdminPerfisNovoRoute: typeof AdminPerfisNovoRoute
  AdminPerfisIndexRoute: typeof AdminPerfisIndexRoute
  AdminPerfisIdEditarRoute: typeof AdminPerfisIdEditarRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDenunciasRoute: AdminDenunciasRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPerfilIdRoute: AdminPerfilIdRoute,
  AdminPerfisNovoRoute: AdminPerfisNovoRoute,
  AdminPerfisIndexRoute: AdminPerfisIndexRoute,
  AdminPerfisIdEditarRoute: AdminPerfisIdEditarRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnuncieRoute: AnuncieRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  PerfilIdRoute: PerfilIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
